### ISSUE TITLE
TypeError: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#484]
https://sentry.io/libcrowds/libcrowds/issues/401354303/

```
TypeError: Object doesn't support property or method 'includes'
  at tags (./node_modules/vue-meta/lib/vue-meta.js:800:14)
  at ref (./node_modules/vue-meta/lib/vue-meta.js:786:1)
  at Object (./node_modules/vue-meta/lib/vue-meta.js:882:1)
  at Anonymous function (./node_modules/vue-meta/lib/vue-meta.js:856:1)
  at Anonymous function (./node_modules/vue-meta/lib/vue-meta.js:919:1)
...
(2 additional frame(s) were not displayed)
```

**Comment by alexandermendes** [comment]
Maybe this was caused by #485

**Comment by alexandermendes** [comment]
After refactoring all meta tags I'll close this for now and reopen if it appears again - hopefully its gone
