### ISSUE TITLE
TypeError: Object doesn't support property or method 'endsWith'

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#485]
https://sentry.io/libcrowds/libcrowds/issues/398705841/

```
TypeError: Object doesn't support property or method 'endsWith'
  at vnode (./pages/collection/_short_name/index.vue?2f4d:1:90)
  at vm (./node_modules/vue/dist/vue.runtime.esm.js:4191:1)
  at value (./node_modules/vue/dist/vue.runtime.esm.js:2570:1)
  at this (./node_modules/vue/dist/vue.runtime.esm.js:2913:1)
  at lr (./node_modules/vue/dist/vue.runtime.esm.js:2900:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by alexandermendes** [comment]
Ahuh, I think this is because we're loading an svg into here

https://github.com/LibCrowds/libcrowds/blob/9f77d0c4bb7d7a91b9f3421a301dfb9d5adbbd22/pages/collection/_short_name/index.vue#L9

**Comment by alexandermendes** [comment]
Seems to have done the trick. We do need a better way to deal with images but this will do for now.
