### ISSUE TITLE
TypeError: Unable to get property 'classList' of undefined or null reference

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#486]
https://sentry.io/libcrowds/libcrowds/issues/401363942/

```
TypeError: Unable to get property 'classList' of undefined or null reference
  at e.a (./node_modules/libcrowds-viewer/dist/main.js:6:265460)
  at boundFn (./node_modules/vue/dist/vue.runtime.esm.js:176:1)
  at on.mouseover (./node_modules/libcrowds-viewer/dist/main.js:13:120039)
  at invoker (./node_modules/vue/dist/vue.runtime.esm.js:1817:1)
  at wrapped (./node_modules/raven-js/src/raven.js:347:1)
```

**Comment by alexandermendes** [comment]
Will revisit if this error appears again
