### ISSUE TITLE
Error: Invalid Date in fecha.format

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#511]
https://sentry.io/libcrowds/libcrowds/issues/399607728/

```
Error: Invalid Date in fecha.format
  at format (./node_modules/libcrowds-viewer/dist/main.js:13:61427)
  at call (./node_modules/libcrowds-viewer/dist/main.js:13:66894)
  at formatValueToField (./node_modules/vue/dist/vue.runtime.esm.js:179:1)
  at value (./node_modules/libcrowds-viewer/dist/main.js:13:43467)
  at call (./node_modules/libcrowds-viewer/dist/main.js:13:68749)
...
(45 additional frame(s) were not displayed)
```

**Comment by alexandermendes** [comment]
This is an issue with the date inputs in vue-form-generator, closing for no longer using this input in tasks. If it pops up again later we can deal with it then.
