### ISSUE TITLE
TypeError: Cannot read property 'mode' of null

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#641]
https://sentry.io/libcrowds/libcrowds/issues/410818610/

```
TypeError: Cannot read property 'mode' of null
  at call (./node_modules/libcrowds-viewer/dist/main.js:18:92496)
  at _render (./node_modules/vue/dist/vue.runtime.esm.js:4191:1)
  at call (./node_modules/vue/dist/vue.runtime.esm.js:2570:1)
  at get (./node_modules/vue/dist/vue.runtime.esm.js:2913:1)
  at new lr (./node_modules/vue/dist/vue.runtime.esm.js:2902:1)
...
(33 additional frame(s) were not displayed)
```

**Comment by alexandermendes** [comment]
Closing for now, will reopen if it still appears later
