### ISSUE TITLE
TypeError: Object doesn't support property or method 'startsWith'

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#709]
https://sentry.io/libcrowds/libcrowds/issues/507788579/

```
TypeError: Object doesn't support property or method 'startsWith'
  at l.head (/_nuxt/pages/collection/_short_name/projects/_id/_presenter.e8451c8fd6a15c8bdb24.js:1:39198)
  at t (/_nuxt/vendor.1098f5c1824c4e9a6342.js:2:2875525)
  at Anonymous function (/_nuxt/vendor.1098f5c1824c4e9a6342.js:2:2875645)
  at t (/_nuxt/vendor.1098f5c1824c4e9a6342.js:2:2875583)
  at Anonymous function (/_nuxt/vendor.1098f5c1824c4e9a6342.js:2:2875645)
...
(9 additional frame(s) were not displayed)
```

Appears on various other pages too, check sentry.

**Comment by alexandermendes** [comment]
So `startsWith` is not supported by IE - replace with `indexOf('foo') == 0`.
