### ISSUE TITLE
TypeError: this.$axios.$get(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by alexandermendes** [LibCrowds/libcrowds#831]
https://sentry.io/libcrowds/libcrowds/issues/592501835/

```
TypeError: this.$axios.$get(...).then(...).catch(...).finally is not a function
  at ["0qsr"]/e.a.methods.loadForumDiscussions (/_nuxt/pages/collection/_short_name/index.35235595219499da4c13.js:1:1274)
  at ["0qsr"]/e.a.mounted (/_nuxt/pages/collection/_short_name/index.35235595219499da4c13.js:1:2812)
  at Me (/_nuxt/vendor.c3744f1be2ca5969889c.js:2:40141)
  at ["/5sW"]/</nn.insert (/_nuxt/vendor.c3744f1be2ca5969889c.js:2:48620)
  at z (/_nuxt/vendor.c3744f1be2ca5969889c.js:2:78142)
...
(17 additional frame(s) were not displayed)
```

**Comment by fencina-bondacom** [comment]
Hi @alexandermendes ! I am having the same error in New Relic, could you fix it?
